const DEFAULT_SIZE = 24;

const ICON_SETS = {
  alert: '',
  'arrow-down': '',
  'arrow-left': '',
  'arrow-right': '',
  'arrow-up': '',
  blank: '',
  check: '',
  'check-indeterminate': '',
  'chevron-down': '',
  'chevron-left': '',
  'chevron-right': '',
  'chevron-up': '',
  'delete-alt': '',
  delete: '',
  filter: '',
  grab: '',
  hide: '',
  menu: '',
  overflow: '',
  plus: '',
  search: '',
  show: '',
  'spinner-track': '',
  spinner: '',
  'triangle-down': '',
  'triangle-left': '',
  'triangle-right': '',
  'triangle-up': '',
  upload: '',
};

export { DEFAULT_SIZE, ICON_SETS };
